# Generated by Django 5.1.6 on 2025-02-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, default='placeholder.jpg', upload_to=''),
        ),
    ]
