# Generated by Django 5.1.6 on 2025-02-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpost_dislikes_blogpost_likes_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(null=True),
        ),
    ]
